name: Supabase Keep Alive

on:
  schedule:
    - cron: '*/15 * * * *' # tiap 15 menit
  workflow_dispatch: # kalau mau manual run

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Print datetime
        run: date -u

      - name: Curl request to Supabase
        run: |
          curl -s "${{ secrets.SUPABASE_URL }}/rest/v1/cabins?select=id&limit=1" \
            -H "apikey: ${{ secrets.SUPABASE_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_KEY }}"
